In [1]:
import pandas as pd
# ^^^ pyforest auto-imports - don't write above this line
pd.set_option("display.max_rows", None, "display.max_columns", None)
pd.reset_option("display.max_rows", "display.max_columns")

In [39]:
# reading csv files
data1 = pd.read_csv('chess_players.csv')
data2 = pd.read_csv('int_chess_stats.csv')
  
# using merge function by setting how='right'. Country is the primary key
df = pd.merge(data1, data2,
                   on='Country',
                   how='left')
  
df

,Unnamed: 0_x,Country Rank,Name,Title,Country,FIDE,Age,K-factor,Unnamed: 0_y,#,Flag,Num Players,Women,% of Women,FIDE Average,GMs,IMs,FMs,WGMs,WIMs,WFMs,Age Avg
0,0,1,"Mirzaad, S.wahabuddin",FM,Afghanistan,1999.0,35,20,132,133,NaN,78,1,1.28,1650,0,0,5,0,0,0,40
1,1,2,"Rahmani, Asef",unranked/unrated,Afghanistan,1871.0,49,20,132,133,NaN,78,1,1.28,1650,0,0,5,0,0,0,40
2,2,3,"Sarwari, Hamidullah",unranked/unrated,Afghanistan,1866.0,33,20,132,133,NaN,78,1,1.28,1650,0,0,5,0,0,0,40
3,3,4,"Sakhawaty, Sepehr",unranked/unrated,Afghanistan,1846.0,19,20,132,133,NaN,78,1,1.28,1650,0,0,5,0,0,0,40
4,4,5,"Jamshedy, Mohammad Ismail",unranked/unrated,Afghanistan,1790.0,78,20,132,133,NaN,78,1,1.28,1650,0,0,5,0,0,0,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175376,175353,155,"Mafukidze, Ruvimbo",unranked/unrated,Zimbabwe,1056.0,24,40,96,97,NaN,287,66,23.00,1617,0,4,0,0,0,0,25
175377,175354,156,Nyarenda Miranda,unranked/unrated,Zimbabwe,1045.0,15,40,96,97,NaN,287,66,23.00,1617,0,4,0,0,0,0,25
175378,175355,157,"Gandiwa, Ellagia",unranked/unrated,Zimbabwe,1029.0,34,40,96,97,NaN,287,66,23.00,1617,0,4,0,0,0,0,25
175379,175356,158,ASHANTI KUVIMBA,unranked/unrated,Zimbabwe,1028.0,18,40,96,97,NaN,287,66,23.00,1617,0,4,0,0,0,0,25
175380,175357,159,"Munyurwa, Seraph",unranked/unrated,Zimbabwe,1014.0,22,40,96,97,NaN,287,66,23.00,1617,0,4,0,0,0,0,25

In [40]:
# Set index to Country
df = df.set_index('Country')
df

,Unnamed: 0_x,Country Rank,Name,Title,FIDE,Age,K-factor,Unnamed: 0_y,#,Flag,Num Players,Women,% of Women,FIDE Average,GMs,IMs,FMs,WGMs,WIMs,WFMs,Age Avg
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,1,"Mirzaad, S.wahabuddin",FM,1999.0,35,20,132,133,NaN,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,1,2,"Rahmani, Asef",unranked/unrated,1871.0,49,20,132,133,NaN,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,2,3,"Sarwari, Hamidullah",unranked/unrated,1866.0,33,20,132,133,NaN,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,3,4,"Sakhawaty, Sepehr",unranked/unrated,1846.0,19,20,132,133,NaN,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,4,5,"Jamshedy, Mohammad Ismail",unranked/unrated,1790.0,78,20,132,133,NaN,78,1,1.28,1650,0,0,5,0,0,0,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,175353,155,"Mafukidze, Ruvimbo",unranked/unrated,1056.0,24,40,96,97,NaN,287,66,23.00,1617,0,4,0,0,0,0,25
Zimbabwe,175354,156,Nyarenda Miranda,unranked/unrated,1045.0,15,40,96,97,NaN,287,66,23.00,1617,0,4,0,0,0,0,25
Zimbabwe,175355,157,"Gandiwa, Ellagia",unranked/unrated,1029.0,34,40,96,97,NaN,287,66,23.00,1617,0,4,0,0,0,0,25
Zimbabwe,175356,158,ASHANTI KUVIMBA,unranked/unrated,1028.0,18,40,96,97,NaN,287,66,23.00,1617,0,4,0,0,0,0,25
Zimbabwe,175357,159,"Munyurwa, Seraph",unranked/unrated,1014.0,22,40,96,97,NaN,287,66,23.00,1617,0,4,0,0,0,0,25

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175381 entries, Afghanistan to Zimbabwe
Data columns (total 21 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0_x  175381 non-null  int64
 1   Country Rank  175381 non-null  int64
 2   Name          175381 non-null  object
 3   Title         175381 non-null  object
 4   FIDE          175381 non-null  float64
 5   Age           175381 non-null  int64
 6   K-factor      175381 non-null  int64
 7   Unnamed: 0_y  175381 non-null  int64
 8   #             175381 non-null  int64
 9   Flag          0 non-null       float64
 10  Num Players   175381 non-null  int64
 11  Women         175381 non-null  int64
 12  % of Women    175381 non-null  float64
 13  FIDE Average  175381 non-null  int64
 14  GMs           175381 non-null  int64
 15  IMs           175381 non-null  int64
 16  FMs           175381 non-null  int64
 17  WGMs          175381 non-null  int64
 18  WIMs          175381 non-null  int64
 19  WFMs          175381 non-null  int64
 20  Age Avg       175381 non-null  int64
dtypes: float64(3), int64(16), object(2)
memory usage: 29.4+ MB

In [42]:
# dropping unamed and flag columns that contain no data or nan
df.drop([col for col in df.columns if "Unnamed" in col], axis=1, inplace=True)
df.drop([col for col in df.columns if "Flag" in col], axis=1, inplace=True)

In [44]:
df.head(20)

,Country Rank,Name,Title,FIDE,Age,K-factor,#,Num Players,Women,% of Women,FIDE Average,GMs,IMs,FMs,WGMs,WIMs,WFMs,Age Avg
Country,,,,,,,,,,,,,,,,,,
Afghanistan,1,"Mirzaad, S.wahabuddin",FM,1999.0,35,20,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,2,"Rahmani, Asef",unranked/unrated,1871.0,49,20,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,3,"Sarwari, Hamidullah",unranked/unrated,1866.0,33,20,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,4,"Sakhawaty, Sepehr",unranked/unrated,1846.0,19,20,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,5,"Jamshedy, Mohammad Ismail",unranked/unrated,1790.0,78,20,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,6,"Mohtaat, Homayoun",unranked/unrated,1751.0,50,20,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,7,"Badghisi, Jarullah",unranked/unrated,1693.0,24,40,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,8,Amini Ezatullah,unranked/unrated,1581.0,41,40,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,9,"Yaqeen, Muizzuddin",unranked/unrated,1536.0,42,20,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,10,"Hosini, Abdulrahim",unranked/unrated,1363.0,35,40,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,11,Samsoor M Shoaib,unranked/unrated,1312.0,33,40,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,12,Shir Ahmad Wahab Zadah,unranked/unrated,1292.0,46,40,133,78,1,1.28,1650,0,0,5,0,0,0,40
Afghanistan,13,"Hamrah, Lidaa",unranked/unrated,1284.0,25,40,133,78,1,1.28,1650,0,0,5,0,0,0,40
Albania,1,"Dervishi, Erald",GM,2511.0,43,10,106,234,17,7.26,1751,1,7,6,0,0,3,43
Albania,2,"Ashiku, Franc",IM,2428.0,29,10,106,234,17,7.26,1751,1,7,6,0,0,3,43
Albania,3,"Pasko, Llambi",IM,2413.0,31,10,106,234,17,7.26,1751,1,7,6,0,0,3,43
Albania,4,"Mehmeti, Dritan",IM,2382.0,44,10,106,234,17,7.26,1751,1,7,6,0,0,3,43
Albania,5,"Seitaj, Ilir",IM,2340.0,65,10,106,234,17,7.26,1751,1,7,6,0,0,3,43
Albania,6,"Qendro, Llambi",IM,2299.0,69,10,106,234,17,7.26,1751,1,7,6,0,0,3,43
Albania,7,"Petritaj, Fotjon",unranked/unrated,2244.0,40,20,106,234,17,7.26,1751,1,7,6,0,0,3,43